
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package practica1conant.Cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GRIS = 24;
  public static final int TIMES = 21;
  public static final int LINEA = 4;
  public static final int PLUS = 18;
  public static final int CURVA = 3;
  public static final int ANIMAR = 17;
  public static final int PARENTECIS_CIERRA = 9;
  public static final int ERROR = 2;
  public static final int CUADRADO = 11;
  public static final int OBJETO = 15;
  public static final int VERDE = 27;
  public static final int ROJO = 29;
  public static final int GRAFICAR = 14;
  public static final int AMARILLO = 28;
  public static final int COMA = 6;
  public static final int NOMBRE = 5;
  public static final int EOF = 0;
  public static final int DIVIDE = 20;
  public static final int MORADO = 25;
  public static final int MINUS = 19;
  public static final int error = 1;
  public static final int NUMERO = 7;
  public static final int POLIGONO = 12;
  public static final int PARENTECIS_ABRE = 8;
  public static final int CIRCULO = 10;
  public static final int AZUL = 30;
  public static final int ROSA = 22;
  public static final int NEGRO = 26;
  public static final int ANTERIOR = 16;
  public static final int NARANJA = 23;
  public static final int RECTANGULO = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "CURVA",
  "LINEA",
  "NOMBRE",
  "COMA",
  "NUMERO",
  "PARENTECIS_ABRE",
  "PARENTECIS_CIERRA",
  "CIRCULO",
  "CUADRADO",
  "POLIGONO",
  "RECTANGULO",
  "GRAFICAR",
  "OBJETO",
  "ANTERIOR",
  "ANIMAR",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "TIMES",
  "ROSA",
  "NARANJA",
  "GRIS",
  "MORADO",
  "NEGRO",
  "VERDE",
  "AMARILLO",
  "ROJO",
  "AZUL"
  };
}

